version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: 1000:1000
    env_file:
      - .env.local
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
